<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Crear CarpetaCrea nuevas carpetas para _06d6c1</name>
   <tag></tag>
   <elementGuidId>cf568346-6e50-478d-acf9-553952796163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.page-body.cyan-general</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e17d8c99-05fc-4f43-85b9-14a60c4a40bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-body cyan-general</value>
      <webElementGuid>1ae08a0f-a9d2-459a-9a3e-c5f732fbba6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crear CarpetaCrea nuevas carpetas para poder guardar datos en ellas.Crear CarpetaSolicitudMira el listado y selecciona una solicitud para poder aprobarla o denegarla.Seleecciona una solicitudDescarga de ArchivosDescarga el archivo de la solicitud para poder verlo.DescargarAprobar o DenegarDecide si aprobar o denegar la solicitud para subir los archivos. Aprobar DenegarHistorialMira los historiales de los datos que has aprobado y denegado.HistorialesUsuariosGestiona los usuarios. Usuarios</value>
      <webElementGuid>59a832c8-8d5e-4bfc-a5d8-384d09d43b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;general&quot;]/div[@class=&quot;page-body cyan-general&quot;]</value>
      <webElementGuid>b99c22ba-bcb9-439c-9463-34b2e2c850f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]</value>
      <webElementGuid>b99a26a0-e32b-43fc-9a72-809bef2d768e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bucket internship-project-21'])[1]/following::div[1]</value>
      <webElementGuid>5ec2a008-5e1a-4875-8a32-118b54b172cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar Sesión'])[1]/following::div[2]</value>
      <webElementGuid>76aa413e-acfa-4c5f-bb42-0743eb60bc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>d4eff1b8-b4b1-48db-a80e-9fc7bfe9d653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Crear CarpetaCrea nuevas carpetas para poder guardar datos en ellas.Crear CarpetaSolicitudMira el listado y selecciona una solicitud para poder aprobarla o denegarla.Seleecciona una solicitudDescarga de ArchivosDescarga el archivo de la solicitud para poder verlo.DescargarAprobar o DenegarDecide si aprobar o denegar la solicitud para subir los archivos. Aprobar DenegarHistorialMira los historiales de los datos que has aprobado y denegado.HistorialesUsuariosGestiona los usuarios. Usuarios' or . = 'Crear CarpetaCrea nuevas carpetas para poder guardar datos en ellas.Crear CarpetaSolicitudMira el listado y selecciona una solicitud para poder aprobarla o denegarla.Seleecciona una solicitudDescarga de ArchivosDescarga el archivo de la solicitud para poder verlo.DescargarAprobar o DenegarDecide si aprobar o denegar la solicitud para subir los archivos. Aprobar DenegarHistorialMira los historiales de los datos que has aprobado y denegado.HistorialesUsuariosGestiona los usuarios. Usuarios')]</value>
      <webElementGuid>aa442cbc-d9a6-4f38-afc2-ba4c9344ef9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
