<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Usuarios</name>
   <tag></tag>
   <elementGuidId>ea63ff14-0416-4b4a-9da7-c52601f0184d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ant-btn.ant-btn-primary.ant-btn-lg.button-register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[6]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ec34744-310b-44f7-b4a5-ca2c9ae99dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/registro</value>
      <webElementGuid>cd1c486a-5622-4b36-bcea-835762df53d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary ant-btn-lg button-register</value>
      <webElementGuid>5d03e083-55e0-4b6d-a0ce-85af58690cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Usuarios</value>
      <webElementGuid>1db08881-4eda-418e-ac0a-30a538dc3ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;general&quot;]/div[@class=&quot;page-body cyan-general&quot;]/div[@class=&quot;container violet&quot;]/div[@class=&quot;contents&quot;]/a[@class=&quot;ant-btn ant-btn-primary ant-btn-lg button-register&quot;]</value>
      <webElementGuid>747076e8-9d34-4dad-a233-c640ad147384</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[6]/div/a</value>
      <webElementGuid>ee53dc10-d949-43aa-a13c-7eb53dc08a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios'])[1]/following::a[1]</value>
      <webElementGuid>fe4f192d-0756-4641-896d-0de7a79f27ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Historiales'])[1]/following::a[1]</value>
      <webElementGuid>ec6f4afa-27f6-4ede-bbec-f53571b4543d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/registro')]</value>
      <webElementGuid>4cea6ad4-4e79-43eb-9911-2ba535168076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a</value>
      <webElementGuid>e9b8e317-e9a5-4d51-9a71-75e7033ff187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/registro']</value>
      <webElementGuid>fd8b9119-a30d-44eb-9285-48ebe23dbb79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
