<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Historiales</name>
   <tag></tag>
   <elementGuidId>38a99112-3773-46ce-9f70-f113b99aef42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[5]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ant-btn.ant-btn-primary.ant-btn-lg.button-history</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69852bfa-ddab-4197-b406-f1e8c7935c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/historiales</value>
      <webElementGuid>496d4e4f-439e-43b9-a636-670863733a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary ant-btn-lg button-history</value>
      <webElementGuid>f4886667-dccd-443a-a19f-9ca822c21c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Historiales</value>
      <webElementGuid>33c205d2-b32b-4588-96b0-cfd2fc1a1c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;general&quot;]/div[@class=&quot;page-body cyan-general&quot;]/div[@class=&quot;container con-download cyan&quot;]/div[@class=&quot;contents&quot;]/a[@class=&quot;ant-btn ant-btn-primary ant-btn-lg button-history&quot;]</value>
      <webElementGuid>a61bd977-16c8-4bdf-a033-d4ce6acf2759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[5]/div/a</value>
      <webElementGuid>098317ac-53b1-47dd-8abb-6c49fdf785ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Historial'])[1]/following::a[1]</value>
      <webElementGuid>1a57ee3a-5d14-44ec-9af8-964055128b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denegar'])[1]/following::a[1]</value>
      <webElementGuid>e8f6e84e-13db-441c-9244-cf42a433a9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios'])[1]/preceding::a[1]</value>
      <webElementGuid>bb0d8410-8679-42eb-b901-73891c4309fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/historiales')]</value>
      <webElementGuid>5b9dd885-4331-43a4-8210-caa4d05cd60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>ade78373-95cb-43a0-8f36-d676f7bfd34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/historiales' and (text() = 'Historiales' or . = 'Historiales')]</value>
      <webElementGuid>b02a27db-e2ac-446e-84ea-005809e3b00c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
