<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Volver</name>
   <tag></tag>
   <elementGuidId>e0663602-ab08-47e8-a9bd-3a1f445d313a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ant-btn.ant-btn-round.ant-btn-primary.ant-btn-lg.btn-return</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f73fc1a3-01a6-47e2-bdee-607cb5dbe18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inicio-admin</value>
      <webElementGuid>395195f2-e426-474b-b561-bf51abaca17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-round ant-btn-primary ant-btn-lg btn-return</value>
      <webElementGuid>bc109597-8052-402f-8520-6457d634b2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Volver</value>
      <webElementGuid>a64932df-98d5-4e75-ac5e-166341c00610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;general&quot;]/div[@class=&quot;page-body cyan&quot;]/a[@class=&quot;ant-btn ant-btn-round ant-btn-primary ant-btn-lg btn-return&quot;]</value>
      <webElementGuid>e7dd8c18-4c63-4e51-9628-56afcd088559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/a</value>
      <webElementGuid>542a3231-aac1-43ff-b903-2e78ed9464cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Historiales'])[1]/following::a[1]</value>
      <webElementGuid>4ab8056f-f43e-448b-9270-d1dc01d9fdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar Sesión'])[1]/following::a[1]</value>
      <webElementGuid>ba0e021d-33a8-423d-ad91-74ce65ea2baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Historial de Aprobados'])[1]/preceding::a[1]</value>
      <webElementGuid>4fb4859d-f1ed-4cfb-bac2-2b5911f9559b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inicio-admin')]</value>
      <webElementGuid>d259062b-dbb5-4dcf-ac4e-51d6229767d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>935e26c5-545e-4579-beb1-d05bdee424e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inicio-admin' and (text() = 'Volver' or . = 'Volver')]</value>
      <webElementGuid>520d19c8-c94c-4ef6-a9d2-8ae19c9f0118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
