<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Iniciar Sesin_formulario_username</name>
   <tag></tag>
   <elementGuidId>5c2941e3-e8a5-4153-9dc2-bcef304d3053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formulario_username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formulario_username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4bfd9f1-db68-44ad-930b-4b3104879e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuario</value>
      <webElementGuid>09ded7dd-360f-4092-8af7-c1c8d4692405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulario_username</value>
      <webElementGuid>81e8d17d-f803-44b2-aba7-7632cb005904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg</value>
      <webElementGuid>61b22e69-471c-4f07-88f7-dbfcedbf9fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1b26cf5-53a2-42f3-85c5-52a8f31c63d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formulario_username&quot;)</value>
      <webElementGuid>69cb0160-7b16-4895-8e46-d93ab3f99d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formulario_username']</value>
      <webElementGuid>458e41f3-cf96-43bc-8d8f-13ef996c7101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formulario']/div/div/div/div/div/span/input</value>
      <webElementGuid>3d45a13c-ed6e-4485-93e4-7a8d40403355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f36969f8-6730-4217-9438-ba5b1030295e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Usuario' and @id = 'formulario_username' and @type = 'text']</value>
      <webElementGuid>812a1d6f-f8ba-4003-902b-ce8e0c088f95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
