<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__swal2-image</name>
   <tag></tag>
   <elementGuidId>427671b0-1393-4e22-8a4c-8a5f1b1111b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='peepo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.swal2-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4986bef2-d5c4-441e-80ba-4bc18648b9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-image</value>
      <webElementGuid>a3eee79c-be9d-481b-b4ed-f99938b16cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/peepo.155980c50930ba391538.gif</value>
      <webElementGuid>3eb4d324-5f88-4a8f-bb08-0d685d98fbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>peepo</value>
      <webElementGuid>5383e129-17ec-41ce-a633-dfa6a2a03118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;swal2-shown swal2-height-auto&quot;]/body[@class=&quot;swal2-shown swal2-height-auto&quot;]/div[@class=&quot;swal2-container swal2-center swal2-backdrop-show&quot;]/div[@class=&quot;swal2-popup swal2-modal swal2-show&quot;]/img[@class=&quot;swal2-image&quot;]</value>
      <webElementGuid>54d80159-41a0-4423-bdad-5901e69ce568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='peepo']</value>
      <webElementGuid>993ae187-8e7d-4173-8c18-dcc56dbc2670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b6c23694-1f50-44dc-bc7b-d06467364ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/peepo.155980c50930ba391538.gif' and @alt = 'peepo']</value>
      <webElementGuid>e05aa423-5272-4ca4-8d7d-49ba5c34cf2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
